// Auto-generated by sync-registry.ts
// Inlines @inkui-cli/core theme and tokens

export const spacing = {
  none: 0,
  xs: 1,
  sm: 1,
  md: 2,
  lg: 3,
  xl: 4,
} as const;

export const borderStyles = {
  single: {
    topLeft: '┌', top: '─', topRight: '┐',
    left: '│', right: '│',
    bottomLeft: '└', bottom: '─', bottomRight: '┘',
    topT: '┬', bottomT: '┴', leftT: '├', rightT: '┤', cross: '┼',
  },
  double: {
    topLeft: '╔', top: '═', topRight: '╗',
    left: '║', right: '║',
    bottomLeft: '╚', bottom: '═', bottomRight: '╝',
    topT: '╦', bottomT: '╩', leftT: '╠', rightT: '╣', cross: '╬',
  },
  rounded: {
    topLeft: '╭', top: '─', topRight: '╮',
    left: '│', right: '│',
    bottomLeft: '╰', bottom: '─', bottomRight: '╯',
    topT: '┬', bottomT: '┴', leftT: '├', rightT: '┤', cross: '┼',
  },
  bold: {
    topLeft: '┏', top: '━', topRight: '┓',
    left: '┃', right: '┃',
    bottomLeft: '┗', bottom: '━', bottomRight: '┛',
    topT: '┳', bottomT: '┻', leftT: '┣', rightT: '┫', cross: '╋',
  },
  ascii: {
    topLeft: '+', top: '-', topRight: '+',
    left: '|', right: '|',
    bottomLeft: '+', bottom: '-', bottomRight: '+',
    topT: '+', bottomT: '+', leftT: '+', rightT: '+', cross: '+',
  },
} as const;

export type BorderStyle = keyof typeof borderStyles;

export const spinnerFrames = {
  dots:   ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'],
  line:   ['−', '\\', '|', '/'],
  arc:    ['◜', '◠', '◝', '◞', '◡', '◟'],
  bounce: ['⣾', '⣽', '⣻', '⢿', '⡿', '⣟', '⣯', '⣷'],
} as const;

export type SpinnerType = keyof typeof spinnerFrames;


export interface InkUITheme {
  colors: {
    primary: string;
    secondary: string;
    success: string;
    warning: string;
    error: string;
    info: string;
    muted: string;
    text: string;
    textInverse: string;
    border: string;
    focus: string;
    selection: string;
  };
  border: 'single' | 'double' | 'rounded' | 'bold' | 'ascii';
}

export const darkTheme: InkUITheme = {
  colors: {
    primary: 'cyan',
    secondary: 'magenta',
    success: 'green',
    warning: 'yellow',
    error: 'red',
    info: 'blue',
    muted: 'gray',
    text: 'white',
    textInverse: 'black',
    border: 'gray',
    focus: 'cyan',
    selection: 'blue',
  },
  border: 'single',
};

export const lightTheme: InkUITheme = {
  colors: {
    primary: 'blue',
    secondary: 'magenta',
    success: 'green',
    warning: 'yellow',
    error: 'red',
    info: 'cyan',
    muted: 'gray',
    text: 'black',
    textInverse: 'white',
    border: 'gray',
    focus: 'blue',
    selection: 'cyan',
  },
  border: 'rounded',
};

